### ISSUE TITLE
选择卡芙卡的语音生成感觉听起来很奇怪 而且吐字也不清楚

### ISSUE THREAD

**Issue by Yakumo-Yukari** [yy4382/genshinvoice-import#2]

**Comment by yy4382** [comment]
既然能生成出来，而且和网页上听起来差不多，那就不是我这个项目的问题。如果听起来和网页上很不一样的话，我会再打开这个 Issue。
吐字不清楚一般是他们训练的模型的问题，这个我也没办法，不过你可以试试在网页上改一些参数
